// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaudiCitiesAI.Infrastructure.Persistence;

#nullable disable

namespace SaudiCitiesAI.Infrastructure.Migrations
{
    [DbContext(typeof(SaudiCitiesDbContext))]
    [Migration("20251224085642_DataSaudi")]
    partial class DataSaudi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SaudiCitiesAI.Domain.Entities.Attraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasColumnName("Category");

                    b.Property<Guid>("CityId")
                        .HasColumnType("char(36)")
                        .HasColumnName("CityId");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("IX_Attractions_CityId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Attractions_Name");

                    b.ToTable("Attractions", (string)null);
                });

            modelBuilder.Entity("SaudiCitiesAI.Domain.Entities.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<long>("OsmId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Population")
                        .HasColumnType("int");

                    b.Property<string>("Wikipedia")
                        .HasColumnType("longtext");

                    b.Property<string>("_knownFor")
                        .HasColumnType("longtext")
                        .HasColumnName("KnownForJson");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Cities_Name");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("SaudiCitiesAI.Domain.Entities.CityAIInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CityId")
                        .HasColumnType("char(36)");

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CityAIInsights");
                });

            modelBuilder.Entity("SaudiCitiesAI.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("ApiKeyHash");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("Email");

                    b.Property<int>("TotalQueries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("TotalQueries");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("SaudiCitiesAI.Domain.Entities.UserAIQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResponseSummary")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserAIQueries");
                });

            modelBuilder.Entity("SaudiCitiesAI.Domain.Entities.UserFavorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("SaudiCitiesAI.Domain.Entities.UserSearchHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<string>("Query")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("Query");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Timestamp");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserSearchHistories_UserId");

                    b.ToTable("UserSearchHistories", (string)null);
                });

            modelBuilder.Entity("SaudiCitiesAI.Domain.Entities.Vision2030Focus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<int>("Category")
                        .HasColumnType("int")
                        .HasColumnName("Category");

                    b.Property<Guid>("CityId")
                        .HasColumnType("char(36)")
                        .HasColumnName("CityId");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("Description");

                    b.HasKey("Id");

                    b.HasIndex("CityId")
                        .HasDatabaseName("IX_Vision2030Focus_CityId");

                    b.ToTable("Vision2030Focus", (string)null);
                });

            modelBuilder.Entity("SaudiCitiesAI.Domain.Entities.Attraction", b =>
                {
                    b.HasOne("SaudiCitiesAI.Domain.Entities.City", null)
                        .WithMany("Attractions")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SaudiCitiesAI.Domain.ValueObjects.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<Guid>("AttractionId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Latitude")
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("Latitude");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("Longitude");

                            b1.HasKey("AttractionId");

                            b1.ToTable("Attractions");

                            b1.WithOwner()
                                .HasForeignKey("AttractionId");
                        });

                    b.Navigation("Coordinates")
                        .IsRequired();
                });

            modelBuilder.Entity("SaudiCitiesAI.Domain.Entities.City", b =>
                {
                    b.OwnsOne("SaudiCitiesAI.Domain.ValueObjects.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<Guid>("CityId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Latitude")
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("Latitude");

                            b1.Property<decimal>("Longitude")
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("Longitude");

                            b1.HasKey("CityId");

                            b1.ToTable("Cities");

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.OwnsOne("SaudiCitiesAI.Domain.ValueObjects.Region", "Region", b1 =>
                        {
                            b1.Property<Guid>("CityId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Name")
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)")
                                .HasColumnName("RegionName");

                            b1.Property<int?>("Type")
                                .HasColumnType("int")
                                .HasColumnName("RegionType");

                            b1.HasKey("CityId");

                            b1.HasIndex("Name")
                                .HasDatabaseName("IX_Cities_RegionName");

                            b1.ToTable("Cities");

                            b1.WithOwner()
                                .HasForeignKey("CityId");
                        });

                    b.Navigation("Coordinates")
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("SaudiCitiesAI.Domain.Entities.UserAIQuery", b =>
                {
                    b.HasOne("SaudiCitiesAI.Domain.Entities.User", null)
                        .WithMany("AIQueries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SaudiCitiesAI.Domain.Entities.UserFavorite", b =>
                {
                    b.HasOne("SaudiCitiesAI.Domain.Entities.User", null)
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SaudiCitiesAI.Domain.Entities.UserSearchHistory", b =>
                {
                    b.HasOne("SaudiCitiesAI.Domain.Entities.User", null)
                        .WithMany("SearchHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SaudiCitiesAI.Domain.Entities.Vision2030Focus", b =>
                {
                    b.HasOne("SaudiCitiesAI.Domain.Entities.City", null)
                        .WithMany("VisionFocus")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SaudiCitiesAI.Domain.Entities.City", b =>
                {
                    b.Navigation("Attractions");

                    b.Navigation("VisionFocus");
                });

            modelBuilder.Entity("SaudiCitiesAI.Domain.Entities.User", b =>
                {
                    b.Navigation("AIQueries");

                    b.Navigation("Favorites");

                    b.Navigation("SearchHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
